version : '3.1'


services:
  postgres:
    image: "postgres"
    container_name: "marvel-card-postgres"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=marvel_schema"
    ports:
      - "5432:5432"