version : '3.1'


services:
  postgres:
    image: "postgres"
    container_name: "marvel-card-postgres"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=marvel_schema"
  application:
    build: ./
    container_name: "java-app"
    volumes:
      - "C:\\Users\\user\\IdeaProjects\\marvel_card\\src\\main\\resources\\static\\image\\:/marvel-app/image/"
    environment:
      - "db-password=root"
      - "db-schema=marvel_schema"
      - "db-url-hosts=marvel-card-postgres"
      - "db-username=postgres"
      - "pathToUpload=/marvel-app/image/"
      - "db-url-port=5432"
    ports:
      - "8091:8091"